const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let bundle,pageIndex=0;
function render(){const q=$('recent-search').value.toLowerCase();const rows=bundle.reviews.filter(r=>(r.text+' '+r.listingId+' '+r.scene).toLowerCase().includes(q));$('recent-review-count').textContent=`展示 ${rows.length} / ${bundle.reviews.length} 条去重评论`;$('recent-reviews').innerHTML=rows.map(r=>`<tr><td><button class="candidate-title" data-details="${esc(r.platform||"Etsy")}:${esc(r.listingId)}">${esc(r.platform||"Etsy")} · ${esc(r.listingId)}</button></td><td>${esc(r.date)}<small>${esc(r.rating)} 星</small></td><td><p>${esc(r.text)}</p></td><td>${esc(r.scene)}<small>初步归类；痛点及付费意愿待验证</small></td></tr>`).join('');}
async function init(){try{const r=await fetch('./recent-data.json');if(!r.ok)throw Error('HTTP '+r.status);bundle=await r.json();if(bundle.reviews.some(r=>r.date<bundle.windowStart||r.date>bundle.windowEnd))throw Error('存在范围外评论');$('recent-summary').textContent=`免费多平台公开页面采集：${bundle.products.length} 个商品当前快照，${bundle.reviews.length} 条近期去重评论。评论日期范围：${bundle.windowStart} — ${bundle.windowEnd}。采集时间：${new Date(bundle.fetchedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}（北京时间）。`;$('recent-limits').innerHTML=bundle.limits.map(x=>`<li>${esc(x)}</li>`).join('');renderProducts();$('candidate-platform').innerHTML='<option value="">全部平台</option>'+[...new Set(bundle.products.map(p=>p.platform))].map(v=>`<option>${esc(v)}</option>`).join('');$('candidate-category').innerHTML='<option value="">全部类别</option>'+[...new Set(bundle.products.map(p=>p.category))].map(v=>`<option>${esc(v)}</option>`).join('');$('recent-import').disabled=false;render();}catch(e){$('recent-summary').textContent='近期数据加载失败：'+e.message;}}
$('recent-search').oninput=()=>{if(bundle)render();};$('recent-import').onclick=()=>window.dispatchEvent(new CustomEvent('liwin-import-recent',{detail:bundle}));init();

function filteredProducts(){const q=$('candidate-search').value.toLowerCase(),platform=$('candidate-platform').value,category=$('candidate-category').value;const rows=bundle.products.filter(p=>(p.title+' '+p.category+' '+p.id).toLowerCase().includes(q)&&(!platform||p.platform===platform)&&(!category||p.category===category));if($('candidate-sort').value==='price')rows.sort((a,b)=>String(a.currency).localeCompare(String(b.currency))||(a.price==null?Infinity:Number(a.price))-(b.price==null?Infinity:Number(b.price)));return rows;}
function renderProducts(){if(!bundle)return;const rows=filteredProducts();pageIndex=Math.min(pageIndex,Math.max(0,Math.ceil(rows.length/50)-1));const visible=rows.slice(pageIndex*50,pageIndex*50+50);
$('recent-products').innerHTML=visible.map(p=>`<tr><td>${thumbnail(p)}<button class="candidate-title" data-details="${esc(p.platform)}:${esc(p.id)}">${esc(p.title)}</button><button class="row-action" data-details="${esc(p.platform)}:${esc(p.id)}">查看已采集资料</button><small>${esc(p.platform||"Etsy")} · ${esc(p.id)} · ${esc(p.category||"桌面收纳")}</small></td><td>${p.price==null?'未知':esc(p.currency+' '+p.price)}<small>采集时当前价格</small></td><td>${p.reviews.length||"未采集"}<small>页面可见近月评论，非完整数量</small></td><td>未知</td><td>未知</td></tr>`).join('');
$('candidate-count').textContent=`筛选 ${rows.length} / ${bundle.products.length} 个 · 第 ${pageIndex+1} / ${Math.max(1,Math.ceil(rows.length/50))} 页`;$('candidate-prev').disabled=pageIndex===0;$('candidate-next').disabled=(pageIndex+1)*50>=rows.length;
}
for(const id of ['candidate-search','candidate-platform','candidate-category','candidate-sort'])$(id).oninput=()=>{pageIndex=0;renderProducts();};
$('candidate-prev').onclick=()=>{pageIndex--;renderProducts();};$('candidate-next').onclick=()=>{pageIndex++;renderProducts();};
$('candidate-export').onclick=()=>{if(!bundle)return;const quote=v=>{let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};const rows=[['平台','类别（初筛）','商品编号','标题','当前价格','币种','来源','采集时间','资质状态'],...filteredProducts().map(p=>[p.platform,p.category,p.id,p.title,p.price,p.currency,p.url,p.fetchedAt,p.qualificationStatus])];const csv='\uFEFF'+rows.map(r=>r.map(quote).join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='liwin-候选商品.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};

function showDetails(key){const p=bundle.products.find(p=>p.platform+':'+p.id===key);if(!p)return;const reviews=bundle.reviews.filter(r=>(r.platform||'Etsy')===p.platform&&r.listingId===p.id);const date=p.fetchedAt?new Date(p.fetchedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}):'未知';
 $('candidate-details-body').innerHTML=`<h3>${esc(p.title)}</h3>${p.localImage?`<img class="candidate-detail-image" src="${esc(p.localImage)}" alt="${esc(p.title)}">`:'<p class="image-unavailable">未取得商品图片</p>'}<div class="notice">这些是采集时保存的资料，无需打开原平台。商品现状可能变化；平台来源链接仍可能受到访问限制。</div><dl class="candidate-facts"><dt>平台 / 商品编号</dt><dd>${esc(p.platform)} / ${esc(p.id)}</dd><dt>类别（初筛）</dt><dd>${esc(p.category||'待确认')}</dd><dt>采集时价格</dt><dd>${p.price==null?'未知':esc(p.currency+' '+p.price)}</dd><dt>采集时间</dt><dd>${esc(date)}（北京时间）</dd><dt>资料来源</dt><dd>${esc(p.sourceField||'公开商品详情页')}</dd><dt>资质状态</dt><dd>${esc(p.qualificationStatus||'待核实')}</dd><dt>上架时间 / 新品状态</dt><dd>${esc(p.listingDate||'未知')} · ${esc(p.newnessStatus||'未核实上架时间')}</dd><dt>月销量 / 广告 CPC</dt><dd>未知</dd></dl><h3>商品说明</h3><p class="saved-description">${esc(p.description||'仅取得搜索列表信息，未取得完整商品说明。')}</p><h3>已取得的近月评论 (${reviews.length})</h3>${reviews.length?reviews.map(r=>`<section class="insight"><strong>${esc(r.date)} · ${esc(r.rating)} 星</strong><p>${esc(r.text)}</p><p>场景线索：${esc(r.scene)}；${esc(r.pain||'痛点未确认')}；付费意愿未验证</p></section>`).join(''):'<p>未取得该商品的近月评论样本，不能理解为该商品没有评论。</p>'}<details><summary>查看原平台来源链接（可能无法访问）</summary><p><a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">打开原商品页面</a></p>${p.evidenceURL?`<p><a href="${esc(p.evidenceURL)}" target="_blank" rel="noopener noreferrer">打开采集来源页面</a></p>`:''}<p>${esc(p.url)}</p></details>`;
 $('candidate-details').showModal();
}
for(const id of ['recent-products','recent-reviews'])$(id).addEventListener('click',e=>{const button=e.target.closest('[data-details]');if(button)showDetails(button.dataset.details);});
$('candidate-details-close').onclick=()=>$('candidate-details').close();

function thumbnail(p){return p.localImage?`<button class="candidate-image-button" data-details="${esc(p.platform)}:${esc(p.id)}" aria-label="查看商品图片和资料"><img class="candidate-thumbnail" src="${esc(p.localImage)}" alt="${esc(p.title)}" loading="lazy"><span class="image-unavailable" hidden>图片加载失败</span></button>`:'<div class="candidate-no-image">未取得图片</div>';}
$('recent-products').addEventListener('error',e=>{if(e.target.tagName==='IMG'){e.target.hidden=true;const fallback=e.target.parentElement.querySelector('.image-unavailable');if(fallback)fallback.hidden=false;}},true);
