import {schemas,names,sites,checkRow,topCompetitors,market,adEstimate,reviewGroups,keywordAudit,selectCore,pilotDecision,csvRows,researchCSV,emptyStore,blankSite,validateBackup} from './research-model.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const storageKey='liwin-research-v2';let store=emptyStore(),project='',site='DE',tab='directions',editing=null,loadError=false;
try{const raw=localStorage.getItem(storageKey);if(raw)store=validateBackup(JSON.parse(raw));}catch{loadError=true;}
const notices={directions:'从关键词、榜单或评论记录候选方向，保留来源和需求假设。各站点独立保存，先创建项目，再录入或导入数据。',competitors:'每站点独立筛选 Top 竞品。相关度为人工审阅评分，不是自动图片识别；月销量须填写数据来源。市场容量是已录入竞品的样本估计。',reviews:'逐条保留原文，确认使用场景、好评点与痛点。重复场景会聚合，未在竞品卖点中找到的场景会列为文案机会线索，须人工复核原语言与同义表达。频繁提及不等于愿意付钱。',keywords:'先决定词，再写文案。按相关度和搜索量推荐最多 50 个核心词；不足 30 个时需补充词库。每个词只允许一个主分配位置，文案完成后核验原词是否出现。',specs:'把评论痛点转成可验收规格、买家卖点与验收方法。没有评论或测试证据的规格应当作为假设继续验证。',pilots:'先设放量门槛，再录入真实测试结果。测试成本包括货款、物流、履约、平台费、税费和退货损耗；广告单列，避免重复。零销量不会判为可放量。'};
function toast(text){$('research-status').textContent=text;}
function save(next){if(loadError){toast('原数据无法读取，请先导出原始备份或恢复有效备份，避免覆盖。');return false;}try{validateBackup(next);localStorage.setItem(storageKey,JSON.stringify(next));store=next;return true;}catch(e){toast('保存失败：'+e.message);return false;}}
function current(){return store.data[project+':'+site]||blankSite();}
function update(fn){if(!project)return toast('请先创建或选择项目');const next=structuredClone(store),key=project+':'+site;next.data[key]??=blankSite();try{fn(next.data[key]);if(save(next)){render();toast('已保存到当前项目与站点');}}catch(e){toast(e.message);}}
function currency(n){return new Intl.NumberFormat('zh-CN',{style:'currency',currency:sites[site][1]}).format(n);}
function pct(n){return n===null?'暂无数据':n.toFixed(1)+'%';}
function metric(a,b){return `<div class="stat"><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`;}
function table(head,rows){return `<div class="table-wrap"><table><thead><tr>${head.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function panel(title,content){return `<section class="insight"><h3>${esc(title)}</h3>${content}</section>`;}
function render(){const s=current();$('research-project').innerHTML='<option value="">选择项目</option>'+store.projects.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');$('research-project').value=project;$('research-site').value=site;
 $('research-tabs').innerHTML=Object.entries(names).map(([k,v])=>`<button role="tab" aria-selected="${tab===k}" data-tab="${k}" class="${tab===k?'active':''}">${v}</button>`).join('');$('research-description').textContent=notices[tab];$('research-title').textContent=names[tab]+' · '+sites[site][0];$('research-add').disabled=!project;
 const rows=s[tab];$('research-grid').innerHTML=rows.length?table([...schemas[tab].map(f=>f.label),'操作'],rows.map(r=>[...schemas[tab].map(f=>esc(r[f.key])),`<button data-edit="${esc(r.id)}">编辑</button> <button data-delete="${esc(r.id)}">删除</button>`])):'<p class="empty-state">暂无记录。添加第一条数据，或下载模板后批量导入 CSV。</p>';
 $('research-insights').innerHTML='';if(tab==='competitors')renderMarket(s);if(tab==='reviews')renderReviews(s);if(tab==='keywords')renderKeywords(s);if(tab==='pilots')renderPilots(s);if(tab==='specs')renderSpecs(s);
}
const configLabels={minSales:'最低月销量',maxAge:'最长上架天数',minTitle:'最低标题相关度',minImage:'最低主图相关度',top:'Top 数量',newDays:'新品定义：上架天数内'};
const economicLabels={cpc:'预估 CPC（站点币种）',cvr:'预估广告转化率 %',price:'目标售价',fixed:'每单固定成本（含采购 / 物流 / 履约）',fees:'除广告外比例费用 %',targetMargin:'目标广告后利润率 %'};
function inputs(values,labels){return Object.entries(labels).map(([k,label])=>`<label>${label}<input name="${k}" type="number" min="${k==='top'?1:k==='cvr'||k==='price'?0.0001:0}" ${['cvr','fees','targetMargin','minTitle','minImage','top'].includes(k)?'max="100"':''} step="any" required value="${esc(values[k])}"></label>`).join('');}
function renderMarket(s){const m=market(s.competitors,Number(s.config.newDays));const top=topCompetitors(s.competitors,s.config);
 const summary=`<div class="stats">${metric('样本月销量',m.count?m.sales:'暂无数据')}${metric('样本月销售额',m.count?currency(m.revenue):'暂无数据')}${metric('新品数量占比',pct(m.newShare))}${metric('新品销量占比',pct(m.newSalesShare))}</div><p>仅统计当前站点已录入竞品，非整个市场容量；同一 ASIN 不重复计入。新品基于上架日期与当前日期计算，未来上架记录不计入。</p>`;
 const filter=`<form id="competitor-filters" class="research-form">${inputs(s.config,configLabels)}<button class="primary">保存筛选条件</button></form>`;
 $('research-insights').innerHTML=panel('市场与新品机会',summary)+panel('Top 竞品筛选',filter+(top.length?table(['竞品','月销量','上架日期','标题相关度','主图相关度'],top.map(r=>[esc(r.asin),esc(r.sales),esc(r.launched),esc(r.titleMatch),esc(r.imageMatch)])):'<p>没有符合条件的竞品。</p>'))+panel('广告与利润敏感性',`<form id="ad-economics" class="research-form">${inputs(s.economics,economicLabels)}<button class="primary">保存并测算</button></form><div id="ad-result"></div><p>获客成本 = CPC ÷ 转化率。广告利润模型与原商品利润表独立，不会叠加原表广告百分比；请使用同一币种和一致税费口径。</p>`);
 try{const a=adEstimate(s.economics);$('ad-result').innerHTML=`<div class="stats">${metric('广告获客成本',currency(a.acquisition))}${metric('广告后单件利润',currency(a.profit))}${metric('广告后利润率',pct(a.margin))}${metric('盈亏平衡 CPC',currency(a.breakCpc))}</div><p>达到目标利润率的 CPC 上限：${a.targetPossible?currency(a.targetCpc):'即使广告零成本也达不到，请调整售价或成本'}。销量和转化率是输入估计，并非平台实时数据。</p>`;}catch(e){$('ad-result').textContent=e.message;}
 $('competitor-filters').onsubmit=e=>{e.preventDefault();update(s=>s.config=Object.fromEntries(new FormData(e.target)));};$('ad-economics').onsubmit=e=>{e.preventDefault();update(s=>s.economics=Object.fromEntries(new FormData(e.target)));};
}
function renderReviews(s){const groups=reviewGroups(s.reviews,s.competitors);$('research-insights').innerHTML=panel('评论证据 → 场景与痛点',groups.length?table(['场景','真实痛点','评论数','好评点','明确付费证据数','原文未强调场景数 / 未知','原文证据','下一步'],groups.map((g,i)=>[esc(g.scene),esc(g.pain||'尚未确认'),g.count,esc(g.positive.join('；')),g.payments,`${g.unpromoted} / ${g.unknown}`,g.evidence.map(r=>`<details><summary>${esc(r.competitor)} · ${esc(r.rating)} 星</summary><p>${esc(r.text)}</p><p>付费证据：${esc(r.paymentEvidence||'无')}</p></details>`).join(''),g.pain?`<button data-convert="${i}">转产品规格</button>`:'先确认痛点'])):'<p>添加评论后，工具按你确认的场景与痛点统计重复证据。</p>');
 $('research-insights').querySelectorAll('[data-convert]').forEach(b=>b.onclick=()=>{const g=groups[Number(b.dataset.convert)];tab='specs';render();openEditor({pain:g.pain,scene:g.scene,evidence:g.evidence.map(r=>r.competitor+'：'+r.text).join('\n')});});
}
function renderKeywords(s){const a=keywordAudit(s.keywords);$('research-insights').innerHTML=panel('核心词收敛与分配校验',`<div class="actions"><button id="suggest-core">按相关度与搜索量推荐核心词</button><button id="export-keywords">导出关键词分配表</button></div><p>核心词 ${a.count} 个 · ${a.ready?'分配校验通过':'仍需完善'}</p>${a.issues.length?'<ul>'+a.issues.map(x=>`<li>${esc(x)}</li>`).join('')+'</ul>':'<p>30–50 个核心词，每词已有唯一主分配位置；已写文案原词校验通过。</p>'}<p>推荐优先相关度 ≥ 60，排序分 = 相关度 × 2 + log10(搜索量 + 1) × 10。推荐后需人工审阅。每站点保留原语言，词形变体请另行审阅。</p>`);$('suggest-core').onclick=()=>update(s=>{const ids=selectCore(s.keywords);s.keywords=s.keywords.map(r=>({...r,core:ids.includes(r.id)?'是':'否'}));});$('export-keywords').onclick=()=>download('关键词分配-'+site+'.csv',researchCSV('keywords',s.keywords));}
function renderPilots(s){$('research-insights').innerHTML=panel('测试后的放量决策',s.pilots.length?table(['测试','真实净利润','退货率','结果'],s.pilots.map(p=>{const d=pilotDecision(p);return [esc(p.name),esc(currency(d.profit)),esc(pct(d.rate)),esc(d.decision)];})):'<p>填写批次、成本、销量和验收结果，按预设门槛评估是否值得上大货。</p>');}
function renderSpecs(s){$('research-insights').innerHTML=panel('从痛点到交付',`<p>已记录 ${s.specs.length} 个改进方向；${s.specs.filter(r=>r.status==='样品合格'||r.status==='已验证付费').length} 个通过样品或付费验证。合格规格再进入小批量测试。</p><button id="spec-to-pilot">创建小批量测试</button>`);$('spec-to-pilot').onclick=()=>{tab='pilots';render();openEditor();};}
function openEditor(prefill=null){if(!project)return toast('请先创建项目');editing=prefill?.id||null;$('research-editor-title').textContent=(editing?'编辑':'添加')+names[tab];$('research-inputs').innerHTML=schemas[tab].map(f=>{let value=prefill?.[f.key]??(f.type==='number'?(f.min??0):f.type==='select'?f.options[0]:'');if(tab==='pilots'&&!editing&&f.key==='maxReturn')value=5;if(tab==='pilots'&&!editing&&f.key==='minSold')value=20;const required=['text','textarea','date'].includes(f.type)?'':'required';return `<label>${esc(f.label)}${f.type==='select'?`<select name="${f.key}">${f.options.map(v=>`<option ${value===v?'selected':''}>${esc(v)}</option>`).join('')}</select>`:f.type==='textarea'?`<textarea name="${f.key}" rows="3">${esc(value)}</textarea>`:`<input name="${f.key}" type="${f.type}" value="${esc(value)}" ${required} ${f.type==='number'?`min="${f.min??0}" ${f.max!==undefined?'max="'+f.max+'"':''} step="any"`:''}>`}</label>`;}).join('');$('research-error').textContent='';$('research-editor').showModal();}
function unique(type,rows){const key={competitors:'asin',keywords:'term'}[type];if(key&&new Set(rows.map(r=>String(r[key]).normalize('NFKC').toLowerCase().trim().replace(/\s+/g,' '))).size!==rows.length)throw Error(type==='competitors'?'当前站点有重复 ASIN，请编辑现有竞品':'当前站点有重复关键词，请编辑现有词');}
$('research-form').onsubmit=e=>{e.preventDefault();try{const row={...Object.fromEntries(new FormData(e.target)),id:editing||crypto.randomUUID()};checkRow(tab,row);let ok=false;update(s=>{const next=editing?s[tab].map(r=>r.id===editing?row:r):[...s[tab],row];unique(tab,next);s[tab]=next;ok=true;});if(ok&&store.data[project+':'+site]?.[tab].some(r=>r.id===row.id))$('research-editor').close();}catch(e){$('research-error').textContent=e.message;}};
$('research-close').onclick=$('research-cancel').onclick=()=>$('research-editor').close();$('research-add').onclick=()=>openEditor();
$('research-tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(b){tab=b.dataset.tab;render();}};
$('research-grid').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.edit)openEditor(current()[tab].find(r=>r.id===b.dataset.edit));if(b.dataset.delete&&confirm('删除这条记录？'))update(s=>s[tab]=s[tab].filter(r=>r.id!==b.dataset.delete));};
$('research-project').onchange=e=>{project=e.target.value;render();};$('research-site').onchange=e=>{site=e.target.value;render();};
$('project-create').onclick=()=>{const name=$('project-name').value.trim();if(!name)return toast('请输入项目名称');const next=structuredClone(store),id=crypto.randomUUID();next.projects.push({id,name});if(save(next)){project=id;$('project-name').value='';render();toast('项目已创建');}};
function download(name,text,type='text/csv'){const url=URL.createObjectURL(new Blob([text],{type:type+';charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('research-template').onclick=()=>download(names[tab]+'-模板.csv',researchCSV(tab,[]));$('research-export').onclick=()=>download(names[tab]+'-'+site+'.csv',researchCSV(tab,current()[tab]));$('research-import').onclick=()=>{if(!project)return toast('请先创建项目');$('research-file').click();};
$('research-file').onchange=async()=>{const file=$('research-file').files[0];const selectedTab=tab,selectedProject=project,selectedSite=site;try{if(!file)return;if(file.size>5*1024*1024)throw Error('请使用小于 5 MB 的 CSV');const rows=csvRows(selectedTab,await file.text()).map(r=>({...r,id:crypto.randomUUID()}));if(tab!==selectedTab||project!==selectedProject||site!==selectedSite)throw Error('导入期间切换了项目或站点，请重新导入');update(s=>{const next=[...s[selectedTab],...rows];unique(selectedTab,next);s[selectedTab]=next;});}catch(e){toast('导入失败：'+e.message);}finally{$('research-file').value='';}};
$('research-backup').onclick=()=>download('liwin-完整调研备份.json',loadError?localStorage.getItem(storageKey)||'':JSON.stringify(store,null,2),'application/json');$('research-restore').onclick=()=>$('backup-file').click();$('backup-file').onchange=async()=>{try{const f=$('backup-file').files[0];if(!f)return;if(f.size>10*1024*1024)throw Error('备份文件过大');const next=validateBackup(JSON.parse(await f.text()));if(!confirm('恢复将替换全部调研项目，建议先导出当前备份。继续？'))return;const previousError=loadError;loadError=false;if(save(next)){project=store.projects[0]?.id||'';render();toast('已恢复全部项目和站点数据');}else loadError=previousError;}catch(e){toast('恢复失败：'+e.message);}finally{$('backup-file').value='';}};
project=store.projects[0]?.id||'';if(project){const storedSite=Object.keys(store.data).find(k=>k.startsWith(project+':'))?.slice(project.length+1);if(storedSite&&sites[storedSite])site=storedSite;}$('research-site').innerHTML=Object.entries(sites).map(([k,v])=>`<option value="${k}">${v[0]} · ${v[1]}</option>`).join('');render();if(loadError)toast('已有调研数据无法读取；请先导出原始备份，当前不会覆盖旧数据。');


window.addEventListener('liwin-import-recent',e=>{
 try{const b=e.detail,id='etsy-recent-'+b.windowEnd;
 if(b.reviews.some(r=>r.date<b.windowStart||r.date>b.windowEnd))throw Error('评论超出日期窗口');
 if(store.projects.some(p=>p.id===id)){project=id;site='ET_US';tab='reviews';render();document.getElementById('recent-status').textContent='已切换到已有近期评论项目，未重复导入。';return;}
 const next=structuredClone(store),data=blankSite();
 data.reviews=b.reviews.map(r=>({id:r.id,competitor:r.listingId,rating:r.rating,text:r.text,scene:r.scene,positive:'',pain:'',willingness:'未验证',paymentEvidence:'',url:r.url+'（评论日期 '+r.date+'；来源：'+r.sourceField+'）'}));
 data.directions=[{id:'etsy-wood-organizer',name:'木质桌面收纳（近期评论线索，待市场验证）',source:'评论',evidence:b.reviews.length+' 条公开页面评论；'+b.windowStart+' 至 '+b.windowEnd+'；样本全部为5星，不能推算月销量或痛点普遍性',url:'https://www.etsy.com/search?q=wood+desk+organizer',hypothesis:'办公桌使用及礼品场景可作为待验证方向；请核实是否包含电器、当前需求及产品合规。'}];
 next.projects.push({id,name:'Etsy · 桌面收纳 · '+b.windowStart+' 至 '+b.windowEnd});next.data[id+':ET_US']=data;
 if(save(next)){project=id;site='ET_US';tab='reviews';render();document.getElementById('recent-status').textContent='已载入 '+b.reviews.length+' 条近期评论，原有项目保留。';document.getElementById('research-workspace').scrollIntoView({behavior:'smooth'});}
 }catch(err){document.getElementById('recent-status').textContent='载入失败：'+err.message;}
});
