import {parseCSV} from './model.js';
export const sites={DE:['德国','EUR'],FR:['法国','EUR'],IT:['意大利','EUR'],ES:['西班牙','EUR'],NL:['荷兰','EUR'],SE:['瑞典','SEK'],PL:['波兰','PLN'],UK:['英国','GBP'],US:['美国','USD']};
const f=(key,label,type='text',extra={})=>({key,label,type,...extra});
export const schemas={
 directions:[f('name','候选方向'),f('source','发现来源','select',{options:['关键词','榜单','评论']}),f('evidence','关键词 / 榜单名称 / 评论证据','textarea'),f('url','来源链接'),f('hypothesis','目标人群与需求假设','textarea')],
 competitors:[f('asin','ASIN / 竞品标识'),f('title','标题'),f('sales','估算月销量','number'),f('price','售价（站点币种）','number'),f('launched','上架日期','date'),f('titleMatch','标题相关度 0–100','number',{max:100}),f('imageMatch','主图相关度 0–100','number',{max:100}),f('claims','竞品强调的场景 / 卖点（分号分隔）','textarea'),f('url','商品链接'),f('source','销量来源与采集日期')],
 reviews:[f('competitor','竞品标识 / ASIN'),f('rating','星级 1–5','number',{min:1,max:5}),f('text','评论原文','textarea'),f('scene','使用场景（人工确认）'),f('positive','体验好的点','textarea'),f('pain','真实痛点（人工确认）','textarea'),f('willingness','付费意愿证据','select',{options:['未验证','原文明确愿意付费','购买 / 预售验证']}),f('paymentEvidence','付费证据原文 / 测试记录','textarea'),f('url','评论来源链接')],
 keywords:[f('term','关键词（站点原语言）'),f('volume','估算月搜索量','number'),f('relevance','产品相关度 0–100','number',{max:100}),f('intent','意图','select',{options:['购买','场景','功能','宽泛']}),f('core','是否核心词','select',{options:['否','是']}),f('placement','唯一主分配位置','select',{options:['未分配','标题','卖点1','卖点2','卖点3','卖点4','卖点5','描述','后台词']}),f('used','文案中的实际使用','select',{options:['待写','已写']}),f('copy','对应文案（包含原词）','textarea'),f('source','词库来源 / 日期')],
 specs:[f('pain','对应痛点'),f('scene','目标场景'),f('spec','可验收产品规格（尺寸 / 材料 / 阈值）','textarea'),f('selling','买家能理解的卖点','textarea'),f('verification','样品验收方法','textarea'),f('status','验证状态','select',{options:['待打样','样品合格','测试失败','已验证付费']}),f('evidence','评论证据 / 样品测试结果','textarea')],
 pilots:[f('name','小批量测试名称'),f('units','投入件数','number'),f('sold','售出件数','number'),f('returned','退货件数','number'),f('adSpend','广告花费（站点币种）','number'),f('revenue','实际销售收入（站点币种）','number'),f('otherCost','除广告外的全部测试成本','number'),f('minSold','放量门槛：最低售出件数','number'),f('maxReturn','放量门槛：最高退货率 %','number',{max:100}),f('minProfit','放量门槛：最低净利润','number'),f('specPassed','关键规格是否验收合格','select',{options:['待验收','是','否']}),f('notes','观察日期 / 买家反馈 / 下一步','textarea')]
};
export const names={directions:'候选方向',competitors:'站点竞品',reviews:'评论与痛点',keywords:'核心词分配',specs:'产品规格',pilots:'小批量测试'};
export function checkRow(type,row){for(const field of schemas[type]){const v=String(row[field.key]??'');if(!v.trim()&&['number','date'].includes(field.type))throw Error(field.label+'不能为空');if(field.type==='number'&&(!Number.isFinite(Number(v))||Number(v)<(field.min??0)||Number(v)>(field.max??Infinity)))throw Error(field.label+'数值不正确');if(field.type==='select'&&!field.options.includes(v))throw Error(field.label+'选项不正确');if(field.type==='date'&&!/^\d{4}-\d{2}-\d{2}$/.test(v))throw Error('上架日期格式应为 YYYY-MM-DD');if(field.type==='date'&&(Number.isNaN(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v))throw Error('上架日期无效');}const required={directions:['name','evidence'],competitors:['asin','title','source'],reviews:['competitor','text','scene'],keywords:['term','source'],specs:['pain','scene','spec','selling','verification'],pilots:['name']}[type];for(const key of required)if(!String(row[key]??'').trim())throw Error(schemas[type].find(f=>f.key===key).label+'不能为空');if(type==='reviews'&&row.willingness!=='未验证'&&!String(row.paymentEvidence||'').trim())throw Error('付费意愿需填写证据');if(type==='pilots'&&(Number(row.sold)>Number(row.units)||Number(row.returned)>Number(row.sold)))throw Error('售出件数不能超过投入，退货不能超过售出');return row;}
export function topCompetitors(rows,config,now=new Date()){const day=86400000;return rows.filter(r=>{const age=(now-new Date(r.launched))/day;return age>=0&&age<=Number(config.maxAge)&&Number(r.sales)>=Number(config.minSales)&&Number(r.titleMatch)>=Number(config.minTitle)&&Number(r.imageMatch)>=Number(config.minImage);}).sort((a,b)=>Number(b.sales)-Number(a.sales)||Number(b.titleMatch)-Number(a.titleMatch)).slice(0,Number(config.top));}
export function market(rows,newDays,now=new Date()){const eligible=rows.filter(r=>new Date(r.launched)<=now);const total=eligible.reduce((s,r)=>s+Number(r.sales),0);const recent=eligible.filter(r=>(now-new Date(r.launched))/86400000<=newDays);const recentSales=recent.reduce((s,r)=>s+Number(r.sales),0);return {count:eligible.length,sales:total,revenue:eligible.reduce((s,r)=>s+Number(r.sales)*Number(r.price),0),newShare:eligible.length?recent.length/eligible.length*100:null,newSalesShare:total?recentSales/total*100:null};}
export function adEstimate(e){const vals=['cpc','cvr','price','fixed','fees','targetMargin'].map(k=>Number(e[k]));if(vals.some(v=>!Number.isFinite(v)||v<0)||Number(e.cvr)<=0||Number(e.cvr)>100||Number(e.price)<=0||Number(e.fees)>100||Number(e.targetMargin)>100)throw Error('请输入有效广告和成本参数，转化率需大于 0');const [cpc,cvr,price,fixed,fees,targetMargin]=vals;const pre=price*(1-fees/100)-fixed;const acquisition=cpc/(cvr/100),profit=pre-acquisition;return {acquisition,profit,margin:profit/price*100,breakCpc:Math.max(0,pre*cvr/100),targetCpc:Math.max(0,(pre-price*targetMargin/100)*cvr/100),targetPossible:pre>=price*targetMargin/100};}
const norm=s=>String(s||'').normalize('NFKC').trim().toLocaleLowerCase().replace(/\s+/g,' ');
export function reviewGroups(reviews,competitors){const groups=new Map();for(const r of reviews){const key=norm(r.scene)+'|'+norm(r.pain);if(!groups.has(key))groups.set(key,{scene:r.scene,pain:r.pain,count:0,positive:new Set(),payments:0,unpromoted:0,unknown:0,evidence:[]});const g=groups.get(key);g.count++;if(r.positive)g.positive.add(r.positive);if(r.willingness!=='未验证'&&r.paymentEvidence)g.payments++;const comp=competitors.find(c=>norm(c.asin)===norm(r.competitor));if(!comp||!comp.claims?.trim())g.unknown++;else if(!norm(comp.claims).includes(norm(r.scene)))g.unpromoted++;g.evidence.push(r);}return [...groups.values()].sort((a,b)=>b.count-a.count).map(g=>({...g,positive:[...g.positive]}));}
export function keywordAudit(rows){const core=rows.filter(r=>r.core==='是'),map=new Map();const issues=[];for(const r of rows){const k=norm(r.term);if(map.has(k))issues.push('重复关键词：'+r.term);map.set(k,r);if(r.core==='是'&&r.placement==='未分配')issues.push('核心词未分配：'+r.term);if(r.used==='已写'&&!norm(r.copy).includes(k))issues.push('文案未包含已写关键词：'+r.term);}if(core.length<30||core.length>50)issues.unshift('核心词应为 30–50 个，当前 '+core.length+' 个');return {count:core.length,issues,ready:issues.length===0};}
export function selectCore(rows){return rows.filter(r=>Number(r.relevance)>=60).sort((a,b)=>(Number(b.relevance)*2+Math.log10(Number(b.volume)+1)*10)-(Number(a.relevance)*2+Math.log10(Number(a.volume)+1)*10)).filter((r,i,a)=>a.findIndex(x=>norm(x.term)===norm(r.term))===i).slice(0,50).map(r=>r.id);}
export function pilotDecision(p){checkRow('pilots',p);const sold=Number(p.sold),rate=sold?Number(p.returned)/sold*100:null,profit=Number(p.revenue)-Number(p.adSpend)-Number(p.otherCost);let decision='继续测试';if(p.specPassed==='否'||profit<Number(p.minProfit)||(rate!==null&&rate>Number(p.maxReturn)))decision='暂缓大货';else if(sold>0&&sold>=Number(p.minSold)&&p.specPassed==='是')decision='达到自定门槛，可评估放量';return {rate,profit,decision};}
export function csvRows(type,text){const rows=parseCSV(text),header=rows.shift(),keys=schemas[type].map(f=>f.key),labels=schemas[type].map(f=>f.label);if(!header||!(header.join('|')===keys.join('|')||header.join('|')===labels.join('|')))throw Error('列名不匹配，请使用本模块模板');if(!rows.length)throw Error('没有数据');return rows.map((r,i)=>{if(r.length!==keys.length)throw Error('第 '+(i+2)+' 行列数不正确');try{return checkRow(type,Object.fromEntries(keys.map((k,j)=>[k,r[j]])));}catch(e){throw Error('第 '+(i+2)+' 行：'+e.message);}});}
export function researchCSV(type,rows){const quote=v=>'"'+String(v??'').replace(/^[\s]*([=+@-])/,"'$1").replaceAll('"','""')+'"';return '\uFEFF'+[schemas[type].map(f=>f.label),...rows.map(r=>schemas[type].map(f=>r[f.key]))].map(r=>r.map(quote).join(',')).join('\r\n');}
export function emptyStore(){return {version:2,projects:[],data:{}};}
export function blankSite(){return {directions:[],competitors:[],reviews:[],keywords:[],specs:[],pilots:[],config:{minSales:0,maxAge:3650,minTitle:60,minImage:60,top:10,newDays:180},economics:{cpc:0.5,cvr:10,price:25,fixed:10,fees:20,targetMargin:25}};}
export function validateBackup(d){if(!d||d.version!==2||!Array.isArray(d.projects)||!d.data||typeof d.data!=='object'||Array.isArray(d.data))throw Error('备份格式不正确');const projectIds=new Set();for(const p of d.projects){if(!p.id||typeof p.name!=='string'||!p.name.trim()||projectIds.has(p.id))throw Error('项目数据不正确');projectIds.add(p.id);}for(const [key,s] of Object.entries(d.data)){const split=key.lastIndexOf(':');if(!projectIds.has(key.slice(0,split))||!sites[key.slice(split+1)])throw Error('备份站点归属不正确');if(!s||!s.config||!s.economics)throw Error('备份缺少站点设置');for(const type of Object.keys(schemas)){if(!Array.isArray(s[type]))throw Error('备份模块数据不正确');const ids=new Set();s[type].forEach(r=>{checkRow(type,r);if(!r.id||ids.has(r.id))throw Error('记录 ID 缺失或重复');ids.add(r.id);});const field={competitors:'asin',keywords:'term'}[type];if(field&&new Set(s[type].map(r=>norm(r[field]))).size!==s[type].length)throw Error('备份存在重复竞品或关键词');}for(const [k,max] of Object.entries({minSales:Infinity,maxAge:Infinity,minTitle:100,minImage:100,top:100,newDays:Infinity})){const n=Number(s.config[k]);if(!Number.isFinite(n)||n<0||n>max||(k==='top'&&n<1))throw Error('备份筛选设置不正确');}adEstimate(s.economics);}return d;}
